[project]
name = "mlops-rapidkl-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Muaz Hazali", email = "100086292+muazhazali@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "h2o>=3.46.0.12",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
    "seaborn>=0.13.2",
]

[project.scripts]
mlops-rapidkl-v2 = "mlops_rapidkl_v2:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
